module.exports = [
  { criterion_id: 'AM-01', domain: 'AM', domain_name: 'Asset Management', title: 'Asset Management Framework', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'AM-02', domain: 'AM', domain_name: 'Asset Management', title: 'Asset Inventory', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'AM-03', domain: 'AM', domain_name: 'Asset Management', title: 'Hardware Asset Inventory', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'AM-04', domain: 'AM', domain_name: 'Asset Management', title: 'Software Asset Inventory', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'AM-05', domain: 'AM', domain_name: 'Asset Management', title: 'Policy for the Proper and Secure Use of Assets', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'AM-06', domain: 'AM', domain_name: 'Asset Management', title: 'Commissioning of Hardware', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'AM-07', domain: 'AM', domain_name: 'Asset Management', title: 'Decommissioning of Hardware', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'AM-08', domain: 'AM', domain_name: 'Asset Management', title: 'Commitment to Proper Use, Safe and Secure Handling and Return of Assets', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'AM-09', domain: 'AM', domain_name: 'Asset Management', title: 'Asset Classification and Labelling', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'AM-10', domain: 'AM', domain_name: 'Asset Management', title: 'Protection of Hardware on Hold', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'AM-11', domain: 'AM', domain_name: 'Asset Management', title: 'Transfer of Hardware', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'AM-12', domain: 'AM', domain_name: 'Asset Management', title: 'Removable Media and Endpoint Devices', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'BCM-01', domain: 'BCM', domain_name: 'Business Continuity Management', title: 'Business Continuity and Emergency Management System', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'BCM-02', domain: 'BCM', domain_name: 'Business Continuity Management', title: 'Business Impact Analysis', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'BCM-03', domain: 'BCM', domain_name: 'Business Continuity Management', title: 'Business Continuity Plans', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'BCM-04', domain: 'BCM', domain_name: 'Business Continuity Management', title: 'Testing Business Continuity', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'COM-01', domain: 'COM', domain_name: 'Communication', title: 'Identification of Applicable Legal, Regulatory, Self-imposed or Contractual Requirements', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'COM-02', domain: 'COM', domain_name: 'Communication', title: 'Policy for Planning and Conducting Audits', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'COM-03', domain: 'COM', domain_name: 'Communication', title: 'Internal Audits of the Information Security Management System', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'COM-04', domain: 'COM', domain_name: 'Communication', title: 'Information on Information Security Performance and Management Assessment of the ISMS', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'COS-01', domain: 'COS', domain_name: 'Customer Orientation and Service Delivery', title: 'Technical Safeguards', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'COS-02', domain: 'COS', domain_name: 'Customer Orientation and Service Delivery', title: 'Security Requirements for Connections in the Cloud Service Provider\'s Network', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'COS-03', domain: 'COS', domain_name: 'Customer Orientation and Service Delivery', title: 'Monitoring of Connections in the Cloud Service Provider\'s Network', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'COS-04', domain: 'COS', domain_name: 'Customer Orientation and Service Delivery', title: 'Cross-Network Access', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'COS-05', domain: 'COS', domain_name: 'Customer Orientation and Service Delivery', title: 'Networks for Administration', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'COS-06', domain: 'COS', domain_name: 'Customer Orientation and Service Delivery', title: 'Separation of Data Traffic in Jointly Used Network Environments', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'COS-07', domain: 'COS', domain_name: 'Customer Orientation and Service Delivery', title: 'Documentation of the Network Topology', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'COS-08', domain: 'COS', domain_name: 'Customer Orientation and Service Delivery', title: 'Policies for Data Transmission', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'CRY-01', domain: 'CRY', domain_name: 'Cryptography', title: 'Policy for the Use of Cryptographic Mechanisms', pqc_relevant: true, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'CRY-02', domain: 'CRY', domain_name: 'Cryptography', title: 'Cryptographic Change Management', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'CRY-03', domain: 'CRY', domain_name: 'Cryptography', title: 'Review of Cryptography Practices', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'CRY-04', domain: 'CRY', domain_name: 'Cryptography', title: 'Protection of Data for Transmission (Transport Protection)', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'CRY-05', domain: 'CRY', domain_name: 'Cryptography', title: 'Encryption of Sensitive Data at Rest', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'CRY-06', domain: 'CRY', domain_name: 'Cryptography', title: 'Secure Key Generation', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'CRY-07', domain: 'CRY', domain_name: 'Cryptography', title: 'Rotation of Cryptographic Keys', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'CRY-08', domain: 'CRY', domain_name: 'Cryptography', title: 'Public-Key Certificate Issuance', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'CRY-09', domain: 'CRY', domain_name: 'Cryptography', title: 'Secure Key Provisioning', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'CRY-10', domain: 'CRY', domain_name: 'Cryptography', title: 'Secure Storage of Keys', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'CRY-11', domain: 'CRY', domain_name: 'Cryptography', title: 'Cryptographic Key Archival', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'CRY-12', domain: 'CRY', domain_name: 'Cryptography', title: 'Cryptographic Key Transition Management', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'CRY-13', domain: 'CRY', domain_name: 'Cryptography', title: 'Handling of Compromised Keys', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'CRY-14', domain: 'CRY', domain_name: 'Cryptography', title: 'Secure Deactivation of Cryptographic Keys', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'CRY-15', domain: 'CRY', domain_name: 'Cryptography', title: 'Requirements for Pre-Shared Keys', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'CRY-16', domain: 'CRY', domain_name: 'Cryptography', title: 'Operational Continuity for Key Management', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'CRY-17', domain: 'CRY', domain_name: 'Cryptography', title: 'Cryptographic Key Lifecycle Management', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'CRY-18', domain: 'CRY', domain_name: 'Cryptography', title: 'Usage of External Key Management Systems', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'CRY-19', domain: 'CRY', domain_name: 'Cryptography', title: 'Secure Handling of Customer Managed Keys', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'DEV-01', domain: 'DEV', domain_name: 'Secure Development and Testing', title: 'Policies for the Development/Procurement of System Components', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'DEV-02', domain: 'DEV', domain_name: 'Secure Development and Testing', title: 'Outsourcing of the Development', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'DEV-03', domain: 'DEV', domain_name: 'Secure Development and Testing', title: 'Policies for Changes to System Components', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'DEV-04', domain: 'DEV', domain_name: 'Secure Development and Testing', title: 'Safety Training and Awareness Programme Regarding Continuous Software Delivery and Associated Systems, Components or Tools', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'DEV-05', domain: 'DEV', domain_name: 'Secure Development and Testing', title: 'Design Documentation for Security Features', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'DEV-06', domain: 'DEV', domain_name: 'Secure Development and Testing', title: 'Risk Assessment, Categorisation and Prioritisation of Changes', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'DEV-07', domain: 'DEV', domain_name: 'Secure Development and Testing', title: 'Testing Changes', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'DEV-08', domain: 'DEV', domain_name: 'Secure Development and Testing', title: 'Logging of Changes', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'DEV-09', domain: 'DEV', domain_name: 'Secure Development and Testing', title: 'Version Control', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'DEV-10', domain: 'DEV', domain_name: 'Secure Development and Testing', title: 'Approvals for Provision in the Production Environment', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'DEV-11', domain: 'DEV', domain_name: 'Secure Development and Testing', title: 'Protection of Development and Test Environments', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'DEV-12', domain: 'DEV', domain_name: 'Secure Development and Testing', title: 'Separation of Environments', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'DEV-13', domain: 'DEV', domain_name: 'Secure Development and Testing', title: 'Transparency about Software Components', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'DEV-14', domain: 'DEV', domain_name: 'Secure Development and Testing', title: 'Secure Use of Third Party Hardware and Software', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'DEV-15', domain: 'DEV', domain_name: 'Secure Development and Testing', title: 'Exceptions to the Change Management Process', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'HR-01', domain: 'HR', domain_name: 'Human Resources', title: 'Verification of Qualification and Trustworthiness', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'HR-02', domain: 'HR', domain_name: 'Human Resources', title: 'Employment Terms and Conditions', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'HR-03', domain: 'HR', domain_name: 'Human Resources', title: 'Security Training and Awareness Programme', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'HR-04', domain: 'HR', domain_name: 'Human Resources', title: 'Disciplinary Measures', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'HR-05', domain: 'HR', domain_name: 'Human Resources', title: 'Responsibilities in the Event of Termination or Change of Employment', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'HR-06', domain: 'HR', domain_name: 'Human Resources', title: 'Non-disclosure Agreements', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'HR-07', domain: 'HR', domain_name: 'Human Resources', title: 'Remote Working - Policy', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'HR-08', domain: 'HR', domain_name: 'Human Resources', title: 'Remote Working - Implementation', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'IAM-01', domain: 'IAM', domain_name: 'Identity and Access Management', title: 'Policy for Identities and Access Rights', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'IAM-02', domain: 'IAM', domain_name: 'Identity and Access Management', title: 'Granting and Change of Identities and Access Rights', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'IAM-03', domain: 'IAM', domain_name: 'Identity and Access Management', title: 'Risk-Based Procedure for Locking and Withdrawal of Identities', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'IAM-04', domain: 'IAM', domain_name: 'Identity and Access Management', title: 'Withdrawal or Adjustment of Access Rights as the Task Area Changes', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'IAM-05', domain: 'IAM', domain_name: 'Identity and Access Management', title: 'Regular Review of Access Rights', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'IAM-06', domain: 'IAM', domain_name: 'Identity and Access Management', title: 'Privileged Access Rights', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'IAM-07', domain: 'IAM', domain_name: 'Identity and Access Management', title: 'Access to Cloud Service Customer Data', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'IAM-08', domain: 'IAM', domain_name: 'Identity and Access Management', title: 'Authentication Mechanisms', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'IAM-09', domain: 'IAM', domain_name: 'Identity and Access Management', title: 'Confidentiality of Authentication Information', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'INQ-01', domain: 'INQ', domain_name: 'Inquiries and Requests', title: 'Legal Assessment of Investigation Requests', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'INQ-02', domain: 'INQ', domain_name: 'Inquiries and Requests', title: 'Informing Cloud Service Customers about Investigation Requests', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'INQ-03', domain: 'INQ', domain_name: 'Inquiries and Requests', title: 'Limiting Access to or Disclosure of Data in Investigation Requests', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'INQ-04', domain: 'INQ', domain_name: 'Inquiries and Requests', title: 'Communication of Technical Procedures for Data Disclosure in Investigation Requests', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OIS-01', domain: 'OIS', domain_name: 'Operational Information Security', title: 'Information Security Management System (ISMS)', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'OIS-02', domain: 'OIS', domain_name: 'Operational Information Security', title: 'Information Security Policy', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OIS-03', domain: 'OIS', domain_name: 'Operational Information Security', title: 'Interfaces and Dependencies', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OIS-04', domain: 'OIS', domain_name: 'Operational Information Security', title: 'Segregation of Duties', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OIS-05', domain: 'OIS', domain_name: 'Operational Information Security', title: 'Threat Intelligence', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OIS-06', domain: 'OIS', domain_name: 'Operational Information Security', title: 'Contact with Relevant Government Agencies and Interest Groups', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OIS-07', domain: 'OIS', domain_name: 'Operational Information Security', title: 'Risk Management Policy', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OIS-08', domain: 'OIS', domain_name: 'Operational Information Security', title: 'Application of the Risk Management Policy - Risk Assessment', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'OIS-09', domain: 'OIS', domain_name: 'Operational Information Security', title: 'Application of the Risk Management Policy - Risk Treatment', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OIS-10', domain: 'OIS', domain_name: 'Operational Information Security', title: 'Information Security in Project Management', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-01', domain: 'OPS', domain_name: 'Operations Security', title: 'Capacity Management - Planning', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-02', domain: 'OPS', domain_name: 'Operations Security', title: 'Capacity Management - Monitoring', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-03', domain: 'OPS', domain_name: 'Operations Security', title: 'Capacity Management - Controlling of Resources', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-04', domain: 'OPS', domain_name: 'Operations Security', title: 'Protection Against Malware - Policies and Procedures', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-05', domain: 'OPS', domain_name: 'Operations Security', title: 'Protection Against Malware - Implementation', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'OPS-06', domain: 'OPS', domain_name: 'Operations Security', title: 'Data Backup and Recovery - Policies and Procedures', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'OPS-07', domain: 'OPS', domain_name: 'Operations Security', title: 'Data Backup and Recovery - Monitoring', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-08', domain: 'OPS', domain_name: 'Operations Security', title: 'Data Backup and Recovery - Regular Testing', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-09', domain: 'OPS', domain_name: 'Operations Security', title: 'Data Backup and Recovery - Storage', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-10', domain: 'OPS', domain_name: 'Operations Security', title: 'Logging and Monitoring - Policies and Procedures', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-11', domain: 'OPS', domain_name: 'Operations Security', title: 'Logging and Monitoring - Policies and Procedures for Handling Cloud Service Derived Data and Account Data', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-12', domain: 'OPS', domain_name: 'Operations Security', title: 'Logging and Monitoring - Access, Retention and Deletion', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-13', domain: 'OPS', domain_name: 'Operations Security', title: 'Logging and Monitoring - Security Information and Event Management', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-14', domain: 'OPS', domain_name: 'Operations Security', title: 'Logging and Monitoring - Retention of the Logging Data', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-15', domain: 'OPS', domain_name: 'Operations Security', title: 'Logging and Monitoring - Accountability', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-16', domain: 'OPS', domain_name: 'Operations Security', title: 'Logging and Monitoring - Configuration', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-17', domain: 'OPS', domain_name: 'Operations Security', title: 'Logging and Monitoring - Availability of the Monitoring Software', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-18', domain: 'OPS', domain_name: 'Operations Security', title: 'Managing Vulnerabilities - Policies and Procedures', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-19', domain: 'OPS', domain_name: 'Operations Security', title: 'Managing Incidents and Crashes - Policies and Procedures', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-20', domain: 'OPS', domain_name: 'Operations Security', title: 'Managing Incidents - Implementation', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-21', domain: 'OPS', domain_name: 'Operations Security', title: 'Managing Crashes - Implementation', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-22', domain: 'OPS', domain_name: 'Operations Security', title: 'Managing Vulnerabilities, Incidents and Crashes - Penetration Tests', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'OPS-23', domain: 'OPS', domain_name: 'Operations Security', title: 'Managing Vulnerabilities, Incidents and Crashes - Measurements, Analyses and Assessments of Procedures', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-24', domain: 'OPS', domain_name: 'Operations Security', title: 'Involvement of Cloud Service Customers in the Event of Incidents', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-25', domain: 'OPS', domain_name: 'Operations Security', title: 'Managing Vulnerabilities, Incidents and Crashes - Vulnerability Scans', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'OPS-26', domain: 'OPS', domain_name: 'Operations Security', title: 'Managing Vulnerabilities, Incidents and Crashes - System Hardening', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'OPS-27', domain: 'OPS', domain_name: 'Operations Security', title: 'Managing Vulnerabilities - Patch Management Policies and Procedures', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'OPS-28', domain: 'OPS', domain_name: 'Operations Security', title: 'Managing Vulnerabilities - Patch Management Implementation', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-29', domain: 'OPS', domain_name: 'Operations Security', title: 'Managing Vulnerabilities, Incidents and Crashes - Externally Sourced Components', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-30', domain: 'OPS', domain_name: 'Operations Security', title: 'Separation of Datasets - Policies and Procedures', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-31', domain: 'OPS', domain_name: 'Operations Security', title: 'Separation of Datasets - Implementation', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-32', domain: 'OPS', domain_name: 'Operations Security', title: 'Confidential Computing - Policies and Procedures', pqc_relevant: false, cc_relevant: true, has_sharpen: false },
  { criterion_id: 'OPS-33', domain: 'OPS', domain_name: 'Operations Security', title: 'Confidential Computing - Remote Attestation', pqc_relevant: false, cc_relevant: true, has_sharpen: false },
  { criterion_id: 'OPS-34', domain: 'OPS', domain_name: 'Operations Security', title: 'Container Management - Policies and Procedures', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'OPS-35', domain: 'OPS', domain_name: 'Operations Security', title: 'Container Management - Implementation', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PI-01', domain: 'PI', domain_name: 'Physical Infrastructure', title: 'Safety of Input and Output Interfaces', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PI-02', domain: 'PI', domain_name: 'Physical Infrastructure', title: 'Contractual Agreements for the Provision of Data', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PI-03', domain: 'PI', domain_name: 'Physical Infrastructure', title: 'Secure Deletion of Data', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PS-01', domain: 'PS', domain_name: 'Procurement and Supplier Management', title: 'Physical Security and Environmental Control Requirements', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PS-02', domain: 'PS', domain_name: 'Procurement and Supplier Management', title: 'Redundancy Model', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'PS-03', domain: 'PS', domain_name: 'Procurement and Supplier Management', title: 'Perimeter Protection', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PS-04', domain: 'PS', domain_name: 'Procurement and Supplier Management', title: 'Physical Site Access Control', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PS-05', domain: 'PS', domain_name: 'Procurement and Supplier Management', title: 'Protection against Threats from Outside and from the Environment', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PS-06', domain: 'PS', domain_name: 'Procurement and Supplier Management', title: 'Protection against Interruptions caused by Power Failures and similar Risks to Supply Facilities', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PS-07', domain: 'PS', domain_name: 'Procurement and Supplier Management', title: 'Surveillance of Operational and Environmental Parameters', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PS-08', domain: 'PS', domain_name: 'Procurement and Supplier Management', title: 'Workplace Security Requirements', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PSS-01', domain: 'PSS', domain_name: 'Product and Service Security', title: 'Guidelines and Recommendations for Cloud Service Customers', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PSS-02', domain: 'PSS', domain_name: 'Product and Service Security', title: 'Identification of Vulnerabilities of the Cloud Service', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PSS-03', domain: 'PSS', domain_name: 'Product and Service Security', title: 'Informing Customers about Known Vulnerabilities', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PSS-04', domain: 'PSS', domain_name: 'Product and Service Security', title: 'Error handling and Logging Mechanisms', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PSS-05', domain: 'PSS', domain_name: 'Product and Service Security', title: 'Authentication Mechanisms', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PSS-06', domain: 'PSS', domain_name: 'Product and Service Security', title: 'Session Management', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PSS-07', domain: 'PSS', domain_name: 'Product and Service Security', title: 'Confidentiality of Authentication Information', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PSS-08', domain: 'PSS', domain_name: 'Product and Service Security', title: 'Roles and Rights Framework', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PSS-09', domain: 'PSS', domain_name: 'Product and Service Security', title: 'Authorisation Mechanisms', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PSS-10', domain: 'PSS', domain_name: 'Product and Service Security', title: 'Software Defined Networking', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PSS-11', domain: 'PSS', domain_name: 'Product and Service Security', title: 'Images for Virtual Machines and Containers', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'PSS-12', domain: 'PSS', domain_name: 'Product and Service Security', title: 'Region of Data Processing and Storage', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'SIM-01', domain: 'SIM', domain_name: 'Security Incident Management', title: 'Policy for Security Incident Management', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'SIM-02', domain: 'SIM', domain_name: 'Security Incident Management', title: 'Security Incident Response Plans', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'SIM-03', domain: 'SIM', domain_name: 'Security Incident Management', title: 'Processing of Security Incidents', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'SIM-04', domain: 'SIM', domain_name: 'Security Incident Management', title: 'Documentation and Reporting of Security Incidents', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'SIM-05', domain: 'SIM', domain_name: 'Security Incident Management', title: 'Duty of the Personnel to Report Security Incidents to a Central Body', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'SIM-06', domain: 'SIM', domain_name: 'Security Incident Management', title: 'Evaluation and Learning Process', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'SP-01', domain: 'SP', domain_name: 'Security Policies', title: 'Documentation, Communication and Provision of Policies and Procedures', pqc_relevant: false, cc_relevant: true, has_sharpen: false },
  { criterion_id: 'SP-02', domain: 'SP', domain_name: 'Security Policies', title: 'Review and Approval of Policies and Procedures', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'SP-03', domain: 'SP', domain_name: 'Security Policies', title: 'Exceptions from Existing Policies and Procedures', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'SSO-01', domain: 'SSO', domain_name: 'Security Assessment and Authorisation', title: 'Policies and Procedures for Controlling and Monitoring Service Organisations', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'SSO-02', domain: 'SSO', domain_name: 'Security Assessment and Authorisation', title: 'Risk Assessment of Service Organisations', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'SSO-03', domain: 'SSO', domain_name: 'Security Assessment and Authorisation', title: 'Data Processing of Service Organisations', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'SSO-04', domain: 'SSO', domain_name: 'Security Assessment and Authorisation', title: 'Directory of Service Organisations', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'SSO-05', domain: 'SSO', domain_name: 'Security Assessment and Authorisation', title: 'Monitoring of Compliance with Requirements', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'SSO-06', domain: 'SSO', domain_name: 'Security Assessment and Authorisation', title: 'Contract Termination Strategy for Service Organisations', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'SSO-07', domain: 'SSO', domain_name: 'Security Assessment and Authorisation', title: 'Ensuring Transparency within Service Organisations', pqc_relevant: false, cc_relevant: false, has_sharpen: true },
  { criterion_id: 'SSO-08', domain: 'SSO', domain_name: 'Security Assessment and Authorisation', title: 'Controlling Exchanges with Suppliers of Functional Components', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'GC-01', domain: 'GC', domain_name: 'Governance and Compliance', title: 'Information on applicable law, jurisdiction, countries, partitions, regions, zones and locations', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'GC-02', domain: 'GC', domain_name: 'Governance and Compliance', title: 'Information on availability and incident handling during regular operation', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'GC-03', domain: 'GC', domain_name: 'Governance and Compliance', title: 'Information on recovery parameters in emergency operation', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'GC-04', domain: 'GC', domain_name: 'Governance and Compliance', title: 'Information on the approach to ensuring service availability', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'GC-05', domain: 'GC', domain_name: 'Governance and Compliance', title: 'Information on how investigation requests from government agencies are handled', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
  { criterion_id: 'GC-06', domain: 'GC', domain_name: 'Governance and Compliance', title: 'Information on certifications or attestations', pqc_relevant: false, cc_relevant: false, has_sharpen: false },
];
