// Cross-framework control mappings — ISO 27001:2022 ↔ NIS-2 ↔ BSI IT-Grundschutz ↔ BSI C5:2026
// Each mapping is stored once (bidirectional lookup handled in the API)
// type: 'direct' = largely equivalent, 'partial' = overlapping coverage, 'related' = topically related
// Generated: 2026-06-11

const mappings = [
  // ─── ISO 27001 ↔ NIS-2 ─────────────────────────────────────────────────────
  { a_framework: 'iso27001', a_ref: '5.1',  b_framework: 'nis2', b_ref: 'Art. 21(2)(a)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.2',  b_framework: 'nis2', b_ref: 'Art. 21(2)(a)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.3',  b_framework: 'nis2', b_ref: 'Art. 21(2)(a)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.4',  b_framework: 'nis2', b_ref: 'Art. 21(2)(a)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.7',  b_framework: 'nis2', b_ref: 'Art. 21(2)(g)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.8',  b_framework: 'nis2', b_ref: 'Art. 21(2)(a)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.9',  b_framework: 'nis2', b_ref: 'Art. 21(2)(i)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.10', b_framework: 'nis2', b_ref: 'Art. 21(2)(i)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.11', b_framework: 'nis2', b_ref: 'Art. 21(2)(i)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.12', b_framework: 'nis2', b_ref: 'Art. 21(2)(i)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.13', b_framework: 'nis2', b_ref: 'Art. 21(2)(i)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.14', b_framework: 'nis2', b_ref: 'Art. 21(2)(i)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.15', b_framework: 'nis2', b_ref: 'Art. 21(2)(i)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.16', b_framework: 'nis2', b_ref: 'Art. 21(2)(i)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.17', b_framework: 'nis2', b_ref: 'Art. 21(2)(j)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.17', b_framework: 'nis2', b_ref: 'Art. 21(2)(i)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.18', b_framework: 'nis2', b_ref: 'Art. 21(2)(i)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.19', b_framework: 'nis2', b_ref: 'Art. 21(2)(d)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.20', b_framework: 'nis2', b_ref: 'Art. 21(2)(d)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.21', b_framework: 'nis2', b_ref: 'Art. 21(2)(d)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.22', b_framework: 'nis2', b_ref: 'Art. 21(2)(d)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.23', b_framework: 'nis2', b_ref: 'Art. 21(2)(d)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.23', b_framework: 'nis2', b_ref: 'Art. 21(2)(e)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.24', b_framework: 'nis2', b_ref: 'Art. 21(2)(b)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.25', b_framework: 'nis2', b_ref: 'Art. 21(2)(b)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.26', b_framework: 'nis2', b_ref: 'Art. 21(2)(b)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.26', b_framework: 'nis2', b_ref: 'Art. 23(1)',     type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.26', b_framework: 'nis2', b_ref: 'Art. 23(3)',     type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.27', b_framework: 'nis2', b_ref: 'Art. 21(2)(b)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.28', b_framework: 'nis2', b_ref: 'Art. 21(2)(b)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.29', b_framework: 'nis2', b_ref: 'Art. 21(2)(c)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.30', b_framework: 'nis2', b_ref: 'Art. 21(2)(c)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.31', b_framework: 'nis2', b_ref: 'Art. 21(2)(a)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.35', b_framework: 'nis2', b_ref: 'Art. 21(2)(f)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.36', b_framework: 'nis2', b_ref: 'Art. 21(2)(f)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '6.1',  b_framework: 'nis2', b_ref: 'Art. 21(2)(i)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '6.2',  b_framework: 'nis2', b_ref: 'Art. 21(2)(i)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '6.3',  b_framework: 'nis2', b_ref: 'Art. 21(2)(f)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '6.3',  b_framework: 'nis2', b_ref: 'Art. 21(2)(g)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '6.4',  b_framework: 'nis2', b_ref: 'Art. 21(2)(i)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '6.5',  b_framework: 'nis2', b_ref: 'Art. 21(2)(i)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '6.6',  b_framework: 'nis2', b_ref: 'Art. 21(2)(i)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.1',  b_framework: 'nis2', b_ref: 'Art. 21(2)(a)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.2',  b_framework: 'nis2', b_ref: 'Art. 21(2)(i)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.3',  b_framework: 'nis2', b_ref: 'Art. 21(2)(i)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.5',  b_framework: 'nis2', b_ref: 'Art. 21(2)(j)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.7',  b_framework: 'nis2', b_ref: 'Art. 21(2)(g)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.8',  b_framework: 'nis2', b_ref: 'Art. 21(2)(e)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.8',  b_framework: 'nis2', b_ref: 'Art. 21(2)(g)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.13', b_framework: 'nis2', b_ref: 'Art. 21(2)(c)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.14', b_framework: 'nis2', b_ref: 'Art. 21(2)(c)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.24', b_framework: 'nis2', b_ref: 'Art. 21(2)(h)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.25', b_framework: 'nis2', b_ref: 'Art. 21(2)(e)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.26', b_framework: 'nis2', b_ref: 'Art. 21(2)(e)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.27', b_framework: 'nis2', b_ref: 'Art. 21(2)(e)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.28', b_framework: 'nis2', b_ref: 'Art. 21(2)(e)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.29', b_framework: 'nis2', b_ref: 'Art. 21(2)(e)', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.30', b_framework: 'nis2', b_ref: 'Art. 21(2)(e)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.31', b_framework: 'nis2', b_ref: 'Art. 21(2)(e)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.32', b_framework: 'nis2', b_ref: 'Art. 21(2)(e)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.33', b_framework: 'nis2', b_ref: 'Art. 21(2)(e)', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.34', b_framework: 'nis2', b_ref: 'Art. 21(2)(e)', type: 'partial' },

  // ─── ISO 27001 ↔ BSI IT-Grundschutz ────────────────────────────────────────
  { a_framework: 'iso27001', a_ref: '5.1',  b_framework: 'bsi_grundschutz', b_ref: 'ISMS.1.A3',       type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.1',  b_framework: 'bsi_grundschutz', b_ref: 'ORP.1.A3',        type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.2',  b_framework: 'bsi_grundschutz', b_ref: 'ISMS.1.A2',       type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.2',  b_framework: 'bsi_grundschutz', b_ref: 'ORP.1.A1',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.2',  b_framework: 'bsi_grundschutz', b_ref: 'ORP.1.A2',        type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.3',  b_framework: 'bsi_grundschutz', b_ref: 'ISMS.1.A2',       type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.4',  b_framework: 'bsi_grundschutz', b_ref: 'ISMS.1.A4',       type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.5',  b_framework: 'bsi_grundschutz', b_ref: 'ORP.1.A5',        type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.7',  b_framework: 'bsi_grundschutz', b_ref: 'ORP.1.A5',        type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.8',  b_framework: 'bsi_grundschutz', b_ref: 'ISMS.1.A6',       type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.15', b_framework: 'bsi_grundschutz', b_ref: 'ORP.4.A1',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.16', b_framework: 'bsi_grundschutz', b_ref: 'ORP.4.A2',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.17', b_framework: 'bsi_grundschutz', b_ref: 'ORP.4.A4',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.17', b_framework: 'bsi_grundschutz', b_ref: 'OPS.1.1.2.A3',    type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.18', b_framework: 'bsi_grundschutz', b_ref: 'ORP.4.A6',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.24', b_framework: 'bsi_grundschutz', b_ref: 'DER.2.1.A1',      type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.25', b_framework: 'bsi_grundschutz', b_ref: 'DER.2.1.A2',      type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.26', b_framework: 'bsi_grundschutz', b_ref: 'DER.2.1.A3',      type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.28', b_framework: 'bsi_grundschutz', b_ref: 'DER.2.1.A4',      type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.29', b_framework: 'bsi_grundschutz', b_ref: 'DER.4.A1',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.30', b_framework: 'bsi_grundschutz', b_ref: 'DER.4.A2',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.30', b_framework: 'bsi_grundschutz', b_ref: 'DER.4.A3',        type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.30', b_framework: 'bsi_grundschutz', b_ref: 'DER.4.A4',        type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.31', b_framework: 'bsi_grundschutz', b_ref: 'ISMS.1.A14',      type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.32', b_framework: 'bsi_grundschutz', b_ref: 'ISMS.1.A14',      type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.35', b_framework: 'bsi_grundschutz', b_ref: 'ISMS.1.A9',       type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.35', b_framework: 'bsi_grundschutz', b_ref: 'DER.3.1.A1',      type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.36', b_framework: 'bsi_grundschutz', b_ref: 'ISMS.1.A8',       type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.36', b_framework: 'bsi_grundschutz', b_ref: 'ISMS.1.A10',      type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.36', b_framework: 'bsi_grundschutz', b_ref: 'DER.3.1.A2',      type: 'direct' },
  { a_framework: 'iso27001', a_ref: '6.1',  b_framework: 'bsi_grundschutz', b_ref: 'ORP.2.A1',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '6.2',  b_framework: 'bsi_grundschutz', b_ref: 'ORP.2.A2',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '6.3',  b_framework: 'bsi_grundschutz', b_ref: 'ORP.2.A4',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '6.3',  b_framework: 'bsi_grundschutz', b_ref: 'ORP.3.A1',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '6.3',  b_framework: 'bsi_grundschutz', b_ref: 'ORP.3.A2',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '6.3',  b_framework: 'bsi_grundschutz', b_ref: 'ORP.3.A3',        type: 'partial' },
  { a_framework: 'iso27001', a_ref: '6.4',  b_framework: 'bsi_grundschutz', b_ref: 'ORP.2.A3',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '6.5',  b_framework: 'bsi_grundschutz', b_ref: 'ORP.2.A3',        type: 'partial' },
  { a_framework: 'iso27001', a_ref: '6.6',  b_framework: 'bsi_grundschutz', b_ref: 'ORP.2.A5',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '6.7',  b_framework: 'bsi_grundschutz', b_ref: 'ORP.1.A6',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '7.1',  b_framework: 'bsi_grundschutz', b_ref: 'INF.1.A1',        type: 'partial' },
  { a_framework: 'iso27001', a_ref: '7.2',  b_framework: 'bsi_grundschutz', b_ref: 'INF.1.A1',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '7.3',  b_framework: 'bsi_grundschutz', b_ref: 'INF.1.A1',        type: 'partial' },
  { a_framework: 'iso27001', a_ref: '7.4',  b_framework: 'bsi_grundschutz', b_ref: 'INF.2.A1',        type: 'partial' },
  { a_framework: 'iso27001', a_ref: '7.6',  b_framework: 'bsi_grundschutz', b_ref: 'INF.2.A1',        type: 'partial' },
  { a_framework: 'iso27001', a_ref: '7.8',  b_framework: 'bsi_grundschutz', b_ref: 'CON.6.A1',        type: 'partial' },
  { a_framework: 'iso27001', a_ref: '7.8',  b_framework: 'bsi_grundschutz', b_ref: 'INF.2.A1',        type: 'partial' },
  { a_framework: 'iso27001', a_ref: '7.10', b_framework: 'bsi_grundschutz', b_ref: 'CON.6.A1',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '7.10', b_framework: 'bsi_grundschutz', b_ref: 'CON.6.A2',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '7.14', b_framework: 'bsi_grundschutz', b_ref: 'CON.6.A1',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '7.14', b_framework: 'bsi_grundschutz', b_ref: 'CON.6.A2',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.2',  b_framework: 'bsi_grundschutz', b_ref: 'ORP.4.A3',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.3',  b_framework: 'bsi_grundschutz', b_ref: 'ORP.4.A3',        type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.3',  b_framework: 'bsi_grundschutz', b_ref: 'OPS.1.1.2.A2',    type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.5',  b_framework: 'bsi_grundschutz', b_ref: 'ORP.4.A5',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.7',  b_framework: 'bsi_grundschutz', b_ref: 'OPS.1.1.4.A1',    type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.7',  b_framework: 'bsi_grundschutz', b_ref: 'OPS.1.1.4.A2',    type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.8',  b_framework: 'bsi_grundschutz', b_ref: 'OPS.1.1.3.A1',    type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.9',  b_framework: 'bsi_grundschutz', b_ref: 'OPS.1.1.2.A1',    type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.9',  b_framework: 'bsi_grundschutz', b_ref: 'SYS.1.1.A1',      type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.9',  b_framework: 'bsi_grundschutz', b_ref: 'SYS.1.1.A2',      type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.9',  b_framework: 'bsi_grundschutz', b_ref: 'SYS.2.1.A1',      type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.10', b_framework: 'bsi_grundschutz', b_ref: 'CON.6.A2',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.13', b_framework: 'bsi_grundschutz', b_ref: 'CON.3.A1',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.13', b_framework: 'bsi_grundschutz', b_ref: 'CON.3.A2',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.14', b_framework: 'bsi_grundschutz', b_ref: 'CON.3.A3',        type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.15', b_framework: 'bsi_grundschutz', b_ref: 'OPS.1.1.5.A1',    type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.15', b_framework: 'bsi_grundschutz', b_ref: 'OPS.1.1.2.A4',    type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.16', b_framework: 'bsi_grundschutz', b_ref: 'OPS.1.1.5.A2',    type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.16', b_framework: 'bsi_grundschutz', b_ref: 'DER.1.A1',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.19', b_framework: 'bsi_grundschutz', b_ref: 'OPS.1.1.3.A1',    type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.20', b_framework: 'bsi_grundschutz', b_ref: 'NET.1.1.A1',      type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.20', b_framework: 'bsi_grundschutz', b_ref: 'NET.1.2.A1',      type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.20', b_framework: 'bsi_grundschutz', b_ref: 'NET.3.2.A1',      type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.21', b_framework: 'bsi_grundschutz', b_ref: 'NET.1.1.A1',      type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.22', b_framework: 'bsi_grundschutz', b_ref: 'NET.1.1.A1',      type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.24', b_framework: 'bsi_grundschutz', b_ref: 'CON.1.A1',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.24', b_framework: 'bsi_grundschutz', b_ref: 'CON.1.A2',        type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.25', b_framework: 'bsi_grundschutz', b_ref: 'APP.3.1.A1',      type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.26', b_framework: 'bsi_grundschutz', b_ref: 'APP.3.1.A1',      type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.28', b_framework: 'bsi_grundschutz', b_ref: 'APP.3.1.A2',      type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.32', b_framework: 'bsi_grundschutz', b_ref: 'OPS.1.1.3.A2',    type: 'direct' },

  // ─── ISO 27001 ↔ BSI C5:2026 ────────────────────────────────────────────────
  { a_framework: 'iso27001', a_ref: '5.1',  b_framework: 'c5', b_ref: 'OIS-01', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.2',  b_framework: 'c5', b_ref: 'OIS-02', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.3',  b_framework: 'c5', b_ref: 'OIS-02', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.4',  b_framework: 'c5', b_ref: 'OIS-03', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.5',  b_framework: 'c5', b_ref: 'COM-01', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.6',  b_framework: 'c5', b_ref: 'OIS-04', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.7',  b_framework: 'c5', b_ref: 'INQ-01', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.7',  b_framework: 'c5', b_ref: 'INQ-02', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.8',  b_framework: 'c5', b_ref: 'OIS-06', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.9',  b_framework: 'c5', b_ref: 'AM-01',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.9',  b_framework: 'c5', b_ref: 'AM-02',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.9',  b_framework: 'c5', b_ref: 'AM-03',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.9',  b_framework: 'c5', b_ref: 'AM-04',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.10', b_framework: 'c5', b_ref: 'AM-05',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.10', b_framework: 'c5', b_ref: 'AM-08',  type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.10', b_framework: 'c5', b_ref: 'AM-12',  type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.11', b_framework: 'c5', b_ref: 'AM-07',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.11', b_framework: 'c5', b_ref: 'AM-08',  type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.12', b_framework: 'c5', b_ref: 'AM-09',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.13', b_framework: 'c5', b_ref: 'AM-09',  type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.14', b_framework: 'c5', b_ref: 'COM-05', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.15', b_framework: 'c5', b_ref: 'IAM-01', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.15', b_framework: 'c5', b_ref: 'IAM-05', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.16', b_framework: 'c5', b_ref: 'IAM-02', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.17', b_framework: 'c5', b_ref: 'IAM-04', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.18', b_framework: 'c5', b_ref: 'IAM-06', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.18', b_framework: 'c5', b_ref: 'IAM-07', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.19', b_framework: 'c5', b_ref: 'SSO-01', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.19', b_framework: 'c5', b_ref: 'SSO-02', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.20', b_framework: 'c5', b_ref: 'SSO-02', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.20', b_framework: 'c5', b_ref: 'SSO-03', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.21', b_framework: 'c5', b_ref: 'SSO-03', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.21', b_framework: 'c5', b_ref: 'SSO-07', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.22', b_framework: 'c5', b_ref: 'SSO-04', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.23', b_framework: 'c5', b_ref: 'SSO-05', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.23', b_framework: 'c5', b_ref: 'OPS-05', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.23', b_framework: 'c5', b_ref: 'OPS-06', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.24', b_framework: 'c5', b_ref: 'SIM-01', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.24', b_framework: 'c5', b_ref: 'SIM-02', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.25', b_framework: 'c5', b_ref: 'SIM-02', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.26', b_framework: 'c5', b_ref: 'SIM-03', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.26', b_framework: 'c5', b_ref: 'SIM-05', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.27', b_framework: 'c5', b_ref: 'SIM-04', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.28', b_framework: 'c5', b_ref: 'SIM-04', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.29', b_framework: 'c5', b_ref: 'BCM-01', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.29', b_framework: 'c5', b_ref: 'OPS-25', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.30', b_framework: 'c5', b_ref: 'BCM-04', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.30', b_framework: 'c5', b_ref: 'OPS-25', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.30', b_framework: 'c5', b_ref: 'OPS-26', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.31', b_framework: 'c5', b_ref: 'COM-01', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.32', b_framework: 'c5', b_ref: 'COM-04', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.33', b_framework: 'c5', b_ref: 'COM-01', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '5.34', b_framework: 'c5', b_ref: 'COM-05', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.35', b_framework: 'c5', b_ref: 'COM-02', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.35', b_framework: 'c5', b_ref: 'OIS-07', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.36', b_framework: 'c5', b_ref: 'COM-03', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '5.36', b_framework: 'c5', b_ref: 'OIS-08', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '6.1',  b_framework: 'c5', b_ref: 'HR-01',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '6.2',  b_framework: 'c5', b_ref: 'HR-02',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '6.2',  b_framework: 'c5', b_ref: 'HR-06',  type: 'partial' },
  { a_framework: 'iso27001', a_ref: '6.3',  b_framework: 'c5', b_ref: 'HR-03',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '6.4',  b_framework: 'c5', b_ref: 'HR-04',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '6.5',  b_framework: 'c5', b_ref: 'HR-05',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '6.6',  b_framework: 'c5', b_ref: 'HR-06',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '7.1',  b_framework: 'c5', b_ref: 'PI-01',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '7.2',  b_framework: 'c5', b_ref: 'PI-02',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '7.2',  b_framework: 'c5', b_ref: 'PS-01',  type: 'partial' },
  { a_framework: 'iso27001', a_ref: '7.3',  b_framework: 'c5', b_ref: 'PI-03',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '7.4',  b_framework: 'c5', b_ref: 'PI-04',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '7.4',  b_framework: 'c5', b_ref: 'PS-02',  type: 'partial' },
  { a_framework: 'iso27001', a_ref: '7.5',  b_framework: 'c5', b_ref: 'PS-03',  type: 'partial' },
  { a_framework: 'iso27001', a_ref: '7.7',  b_framework: 'c5', b_ref: 'PI-03',  type: 'partial' },
  { a_framework: 'iso27001', a_ref: '7.8',  b_framework: 'c5', b_ref: 'AM-10',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '7.8',  b_framework: 'c5', b_ref: 'PI-05',  type: 'partial' },
  { a_framework: 'iso27001', a_ref: '7.9',  b_framework: 'c5', b_ref: 'AM-10',  type: 'partial' },
  { a_framework: 'iso27001', a_ref: '7.9',  b_framework: 'c5', b_ref: 'AM-11',  type: 'partial' },
  { a_framework: 'iso27001', a_ref: '7.9',  b_framework: 'c5', b_ref: 'PI-06',  type: 'partial' },
  { a_framework: 'iso27001', a_ref: '7.10', b_framework: 'c5', b_ref: 'AM-12',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '7.11', b_framework: 'c5', b_ref: 'PSS-01', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '7.12', b_framework: 'c5', b_ref: 'PSS-02', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '7.13', b_framework: 'c5', b_ref: 'PSS-03', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '7.14', b_framework: 'c5', b_ref: 'AM-07',  type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.2',  b_framework: 'c5', b_ref: 'IAM-05', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.2',  b_framework: 'c5', b_ref: 'IAM-06', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.3',  b_framework: 'c5', b_ref: 'IAM-06', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.3',  b_framework: 'c5', b_ref: 'IAM-07', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.4',  b_framework: 'c5', b_ref: 'IAM-08', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.5',  b_framework: 'c5', b_ref: 'IAM-03', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.6',  b_framework: 'c5', b_ref: 'OPS-01', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.7',  b_framework: 'c5', b_ref: 'OPS-07', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.8',  b_framework: 'c5', b_ref: 'INQ-01', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.8',  b_framework: 'c5', b_ref: 'INQ-02', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.8',  b_framework: 'c5', b_ref: 'OPS-08', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.9',  b_framework: 'c5', b_ref: 'OPS-01', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.9',  b_framework: 'c5', b_ref: 'OPS-12', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.13', b_framework: 'c5', b_ref: 'OPS-22', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.14', b_framework: 'c5', b_ref: 'OPS-27', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.15', b_framework: 'c5', b_ref: 'OPS-09', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.16', b_framework: 'c5', b_ref: 'OPS-10', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.17', b_framework: 'c5', b_ref: 'OPS-10', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.18', b_framework: 'c5', b_ref: 'IAM-07', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.18', b_framework: 'c5', b_ref: 'SP-01',  type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.19', b_framework: 'c5', b_ref: 'OPS-08', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.20', b_framework: 'c5', b_ref: 'OPS-11', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.20', b_framework: 'c5', b_ref: 'CRY-04', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.21', b_framework: 'c5', b_ref: 'OPS-11', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.22', b_framework: 'c5', b_ref: 'OPS-11', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.22', b_framework: 'c5', b_ref: 'OPS-32', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.22', b_framework: 'c5', b_ref: 'OPS-33', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.24', b_framework: 'c5', b_ref: 'CRY-01', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.24', b_framework: 'c5', b_ref: 'CRY-02', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.24', b_framework: 'c5', b_ref: 'CRY-03', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.24', b_framework: 'c5', b_ref: 'CRY-04', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.25', b_framework: 'c5', b_ref: 'DEV-01', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.26', b_framework: 'c5', b_ref: 'DEV-06', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.27', b_framework: 'c5', b_ref: 'DEV-05', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.28', b_framework: 'c5', b_ref: 'DEV-02', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.29', b_framework: 'c5', b_ref: 'DEV-04', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.30', b_framework: 'c5', b_ref: 'DEV-04', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.31', b_framework: 'c5', b_ref: 'DEV-03', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.31', b_framework: 'c5', b_ref: 'OPS-32', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.31', b_framework: 'c5', b_ref: 'OPS-33', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.32', b_framework: 'c5', b_ref: 'OPS-04', type: 'direct' },
  { a_framework: 'iso27001', a_ref: '8.33', b_framework: 'c5', b_ref: 'DEV-04', type: 'partial' },
  { a_framework: 'iso27001', a_ref: '8.34', b_framework: 'c5', b_ref: 'OPS-09', type: 'partial' },
];

// Build reverse index for fast lookup: framework+ref → array of mappings
const index = {};
for (const m of mappings) {
  const keyA = `${m.a_framework}:${m.a_ref}`;
  const keyB = `${m.b_framework}:${m.b_ref}`;
  if (!index[keyA]) index[keyA] = [];
  if (!index[keyB]) index[keyB] = [];
  index[keyA].push({ framework: m.b_framework, ref: m.b_ref, type: m.type });
  index[keyB].push({ framework: m.a_framework, ref: m.a_ref, type: m.type });
}

const lookup = (framework, ref) => index[`${framework}:${ref}`] || [];

const stats = () => ({
  total: mappings.length,
  byPair: {
    'iso27001-nis2': mappings.filter(m =>
      (m.a_framework === 'iso27001' && m.b_framework === 'nis2') ||
      (m.a_framework === 'nis2' && m.b_framework === 'iso27001')
    ).length,
    'iso27001-c5': mappings.filter(m =>
      (m.a_framework === 'iso27001' && m.b_framework === 'c5') ||
      (m.a_framework === 'c5' && m.b_framework === 'iso27001')
    ).length,
    'iso27001-bsi_grundschutz': mappings.filter(m =>
      (m.a_framework === 'iso27001' && m.b_framework === 'bsi_grundschutz') ||
      (m.a_framework === 'bsi_grundschutz' && m.b_framework === 'iso27001')
    ).length,
  },
});

module.exports = { mappings, lookup, stats };
