// NIS-2-Richtlinie (EU 2022/2555) — Sicherheitsmassnahmen Art. 21 und
// Meldepflichten Art. 23, mit der Zuordnung zum deutschen Umsetzungsgesetz.
//
// Zwei Ebenen: Die Oberkriterien sind die gesetzlichen Anker und bleiben im
// Wortlaut nah am Gesetz. Darunter stehen die Unterkriterien — das, was ein
// Auditor tatsaechlich sehen will. Eine Massnahme wie "Aufrechterhaltung des
// Betriebs" ist als eine Zeile nicht pruefbar; sie zerfaellt in
// Auswirkungsanalyse, Backup-Konzept, Wiederherstellungstests, Notfallplaene
// und Krisenkommunikation, und jedes davon ist einzeln umgesetzt oder nicht.
// Gezaehlt werden deshalb die Unterkriterien; ein Oberkriterium mit Kindern
// ist eine Klammer und leitet seinen Stand aus ihnen ab.
//
// bsig_ref traegt die Fundstelle im deutschen Recht, denn geprueft wird eine
// deutsche Einrichtung am BSIG und nicht an der Richtlinie. Die zehn
// Massnahmen aus Art. 21(2)(a)-(j) stehen dort als § 30 Abs. 2 Nr. 1-10.
// Wo die Zuordnung hier fehlt, ist sie nicht belegt — eine geratene
// Paragraphenangabe waere in einem Compliance-Werkzeug schlimmer als keine.
const catalog = [
  {
    article_ref: 'Art. 21(2)(a)',
    bsig_ref: '§ 30 Abs. 2 Nr. 1 BSIG',
    category: 'Risikoanalyse & Sicherheitsrichtlinien',
    title: 'Konzepte für Risikoanalyse und Sicherheit für Informationssysteme',
    description: 'Einrichtung und Umsetzung von Konzepten zur Risikoanalyse und zur Sicherheit von Informationssystemen (Informationssicherheitsmanagementsystem — ISMS).',
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: 'Art. 21(2)(b)',
    bsig_ref: '§ 30 Abs. 2 Nr. 2 BSIG',
    category: 'Vorfallbewältigung',
    title: 'Bewältigung von Sicherheitsvorfällen',
    description: 'Konzepte und Verfahren zur Bewältigung von Sicherheitsvorfällen, einschließlich Erkennung, Eskalation, Reaktion und Wiederherstellung.',
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: 'Art. 21(2)(c)',
    bsig_ref: '§ 30 Abs. 2 Nr. 3 BSIG',
    category: 'Business Continuity',
    title: 'Aufrechterhaltung des Betriebs, Backup-Management und Disaster Recovery',
    description: 'Maßnahmen zur Aufrechterhaltung des Betriebs, inkl. Backup-Management, Wiederherstellung im Katastrophenfall und Krisenmanagement.',
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: 'Art. 21(2)(d)',
    bsig_ref: '§ 30 Abs. 2 Nr. 4 BSIG',
    category: 'Lieferkettensicherheit',
    title: 'Sicherheit der Lieferkette',
    description: 'Sicherheit der Lieferkette einschließlich sicherheitsbezogener Aspekte der Beziehungen zwischen den einzelnen Einrichtungen und ihren unmittelbaren Anbietern oder Diensteanbietern.',
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: 'Art. 21(2)(e)',
    bsig_ref: '§ 30 Abs. 2 Nr. 5 BSIG',
    category: 'Sicherheit im Erwerb',
    title: 'Sicherheit beim Erwerb, bei der Entwicklung und Wartung von Netz- und Informationssystemen',
    description: 'Sicherheitsanforderungen beim Erwerb, bei der Entwicklung und Wartung von Netz- und Informationssystemen, einschließlich Schwachstellenmanagement und Offenlegung von Schwachstellen.',
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: 'Art. 21(2)(f)',
    bsig_ref: '§ 30 Abs. 2 Nr. 6 BSIG',
    category: 'Wirksamkeit von Maßnahmen',
    title: 'Bewertung der Wirksamkeit von Risikomanagementmaßnahmen',
    description: 'Konzepte und Verfahren zur Bewertung der Wirksamkeit der Maßnahmen zur Cybersicherheits-Risikomanagement, einschließlich interner Audits und Review-Prozesse.',
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: 'Art. 21(2)(g)',
    bsig_ref: '§ 30 Abs. 2 Nr. 7 BSIG',
    category: 'Cyberhygiene & Schulungen',
    title: 'Grundlegende Verfahren zur Cyberhygiene und Schulungen',
    description: 'Grundlegende Verfahren im Bereich Cyberhygiene sowie Cybersicherheitsschulungen für Mitarbeitende und Führungskräfte.',
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: 'Art. 21(2)(h)',
    bsig_ref: '§ 30 Abs. 2 Nr. 8 BSIG',
    category: 'Kryptografie',
    title: 'Konzepte und Verfahren für den Einsatz von Kryptografie',
    description: 'Konzepte und Verfahren für den Einsatz von Kryptografie und gegebenenfalls Verschlüsselung.',
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: 'Art. 21(2)(i)',
    bsig_ref: '§ 30 Abs. 2 Nr. 9 BSIG',
    category: 'Personalsicherheit & Zugangssteuerung',
    title: 'Sicherheit des Personals, Konzepte für die Zugangssteuerung und Asset Management',
    description: 'Maßnahmen zur Sicherheit des Personals, Konzepte für die Zugangssteuerung und das Asset Management, einschließlich Need-to-Know-Prinzip und Zero-Trust-Ansätze.',
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: 'Art. 21(2)(j)',
    bsig_ref: '§ 30 Abs. 2 Nr. 10 BSIG',
    category: 'Multi-Faktor-Authentifizierung',
    title: 'Verwendung von Multi-Faktor-Authentifizierung oder kontinuierlicher Authentifizierung',
    description: 'Verwendung von Multi-Faktor-Authentifizierungslösungen oder kontinuierlichen Authentifizierungslösungen sowie gesicherter Sprach-, Video- und Textkommunikation und gesicherter Notfallkommunikation.',
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: 'Art. 23(1)',
    category: 'Meldepflichten',
    title: 'Meldung erheblicher Sicherheitsvorfälle (Frühwarnung innerhalb 24h)',
    description: 'Erhebliche Sicherheitsvorfälle müssen der zuständigen Behörde unverzüglich, spätestens 24 Stunden nach Kenntnisnahme, als Frühwarnung gemeldet werden. Fuer nicht direkt betroffene Einrichtungen entfaellt diese Pflicht gegenueber der Behoerde; an ihre Stelle tritt in der Regel eine vertragliche Meldepflicht gegenueber dem betroffenen Auftraggeber.',
    applicability: { essential: 'required', important: 'required', indirect: 'not_applicable' },
  },
  {
    article_ref: 'Art. 23(2)',
    category: 'Meldepflichten',
    title: 'Aktualisierte Meldung innerhalb 72 Stunden',
    description: 'Unverzüglich, spätestens 72 Stunden nach Kenntnisnahme, muss eine aktualisierte Meldung mit erster Einschätzung des Vorfalls, Schweregrad und Indikatoren für Kompromittierung übermittelt werden. Fuer nicht direkt betroffene Einrichtungen entfaellt diese Pflicht gegenueber der Behoerde; an ihre Stelle tritt in der Regel eine vertragliche Meldepflicht gegenueber dem betroffenen Auftraggeber.',
    applicability: { essential: 'required', important: 'required', indirect: 'not_applicable' },
  },
  {
    article_ref: 'Art. 23(4)',
    category: 'Meldepflichten',
    title: 'Abschlussbericht spätestens einen Monat nach Vorfall',
    description: 'Spätestens einen Monat nach Übermittlung der Meldung gemäß Art. 23(2) ist ein Abschlussbericht mit Beschreibung des Vorfalls, Angabe der Ursachen und getroffenen Abhilfemaßnahmen zu übermitteln. Fuer nicht direkt betroffene Einrichtungen entfaellt diese Pflicht gegenueber der Behoerde; an ihre Stelle tritt in der Regel eine vertragliche Meldepflicht gegenueber dem betroffenen Auftraggeber.',
    applicability: { essential: 'required', important: 'required', indirect: 'not_applicable' },
  },
  {
    article_ref: 'Art. 20(1)',
    category: 'Governance & Managementhaftung',
    title: 'Billigung und Ueberwachung der Risikomanagementmassnahmen durch die Leitung',
    description: 'Die Leitungsorgane billigen die Massnahmen zum Management von Cybersicherheitsrisiken, ueberwachen ihre Umsetzung und haften fuer Verstoesse. Nachweis sind dokumentierte Entscheidungen — Budget, Freigaben, Managementbewertung.',
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: 'Art. 20(2)',
    category: 'Governance & Managementhaftung',
    title: 'Schulung der Leitungsorgane',
    description: 'Mitglieder der Leitungsorgane nehmen an Schulungen teil, um Risiken und Managementpraktiken im Bereich der Cybersicherheit bewerten zu koennen. Vergleichbare Schulungen sind den Beschaeftigten regelmaessig anzubieten.',
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: 'Art. 21(3)',
    category: 'Lieferkettensicherheit',
    title: 'Bewertung der Sicherheitspraktiken unmittelbarer Anbieter',
    description: 'Bei der Bewertung der Lieferkette sind die spezifischen Schwachstellen der einzelnen Anbieter, die Qualitaet ihrer Produkte und ihrer Cybersicherheitspraxis sowie die Ergebnisse koordinierter Risikobewertungen zu beruecksichtigen.',
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: 'Art. 21(4)',
    category: 'Korrekturmassnahmen',
    title: 'Unverzuegliche Korrekturmassnahmen bei Nichteinhaltung',
    description: 'Wird festgestellt, dass die Anforderungen nicht eingehalten werden, sind unverzueglich alle notwendigen, geeigneten und verhaeltnismaessigen Korrekturmassnahmen zu ergreifen. Nachweis ist ein gefuehrtes Korrekturmassnahmenprotokoll mit Verantwortlichen, Fristen und Status.',
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: 'Art. 21(2)(d) ff.',
    category: 'Lieferkettensicherheit',
    title: 'Nachweisfaehigkeit gegenueber betroffenen Auftraggebern',
    description: 'Wer selbst nicht in den Anwendungsbereich faellt, aber eine betroffene Einrichtung beliefert, bekommt deren Anforderungen vertraglich durchgereicht: Sicherheitsklauseln, Auskunft ueber Vorfaelle, Nachweise und Auditrechte. Dieses Kriterium buendelt, was dafuer vorgehalten werden muss — fuer direkt Betroffene eine Empfehlung, fuer indirekt Betroffene der eigentliche Pruefpunkt.',
    applicability: { essential: 'recommended', important: 'recommended', indirect: 'required' },
  },
  {
    article_ref: "Art. 20(1).1",
    parent_ref: "Art. 20(1)",
    category: "Governance & Managementhaftung",
    title: "Billigung der Risikomanagementmassnahmen dokumentiert",
    description: "Die Leitung hat den Massnahmenkatalog formal gebilligt. Nachweis ist ein datierter Beschluss, ein Protokoll oder eine unterzeichnete Leitlinie — nicht die Massnahmen selbst.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 20(1).2",
    parent_ref: "Art. 20(1)",
    category: "Governance & Managementhaftung",
    title: "Regelmaessige Berichterstattung an die Leitung",
    description: "Turnus, Inhalt und Empfaengerkreis der Sicherheitsberichte sind festgelegt, und die Berichte liegen vor. Ohne Bericht keine Ueberwachung, und ohne Ueberwachung keine Erfuellung der Aufsichtspflicht.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 20(1).3",
    parent_ref: "Art. 20(1)",
    category: "Governance & Managementhaftung",
    title: "Ressourcen und Budget zugewiesen",
    description: "Fuer die beschlossenen Massnahmen sind Mittel und Personal zugeordnet. Ein gebilligter Katalog ohne Budget ist eine Absichtserklaerung.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 20(1).4",
    parent_ref: "Art. 20(1)",
    category: "Governance & Managementhaftung",
    title: "Verantwortlichkeiten benannt und bekannt",
    description: "Die Rolle fuer Informationssicherheit ist besetzt, schriftlich bestellt und in der Organisation bekannt gemacht, mit Vertretungsregelung.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 20(2).1",
    parent_ref: "Art. 20(2)",
    category: "Governance & Managementhaftung",
    title: "Schulung der Leitungsorgane durchgefuehrt und belegt",
    description: "Teilnahme, Inhalt und Datum sind festgehalten. Die Pflicht trifft die Leitungsmitglieder persoenlich; eine Teilnahmebestaetigung genuegt als Nachweis.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 20(2).2",
    parent_ref: "Art. 20(2)",
    category: "Governance & Managementhaftung",
    title: "Wiederholungsturnus festgelegt",
    description: "Die Schulung ist kein einmaliger Akt. Ein festgelegter Turnus und der naechste Termin gehoeren dazu.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 21(2)(a).1",
    bsig_ref: "§ 30 Abs. 2 Nr. 1 BSIG",
    parent_ref: "Art. 21(2)(a)",
    category: "Risikoanalyse & Sicherheitsrichtlinien",
    title: "Geltungsbereich des ISMS festgelegt",
    description: "Welche Standorte, Prozesse, Systeme und Gesellschaften erfasst sind, ist schriftlich abgegrenzt. Ohne Geltungsbereich laesst sich keine Aussage darueber treffen, was geprueft wurde und was nicht.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(a).2",
    bsig_ref: "§ 30 Abs. 2 Nr. 1 BSIG",
    parent_ref: "Art. 21(2)(a)",
    category: "Risikoanalyse & Sicherheitsrichtlinien",
    title: "Leitlinie zur Informationssicherheit in Kraft",
    description: "Von der Leitung in Kraft gesetzt, den Beschaeftigten bekannt gemacht, mit Gueltigkeitsdatum und Revisionsstand.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(a).3",
    bsig_ref: "§ 30 Abs. 2 Nr. 1 BSIG",
    parent_ref: "Art. 21(2)(a)",
    category: "Risikoanalyse & Sicherheitsrichtlinien",
    title: "Methodik der Risikobewertung festgelegt",
    description: "Skala, Bewertungskriterien, Akzeptanzschwellen und Zustaendigkeiten sind definiert — sonst ist jede Bewertung eine Einzelmeinung und Ergebnisse sind ueber die Zeit nicht vergleichbar.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(a).4",
    bsig_ref: "§ 30 Abs. 2 Nr. 1 BSIG",
    parent_ref: "Art. 21(2)(a)",
    category: "Risikoanalyse & Sicherheitsrichtlinien",
    title: "Schutzbedarf der Assets festgestellt",
    description: "Je Asset ist der Schutzbedarf fuer Vertraulichkeit, Integritaet und Verfuegbarkeit bestimmt und begruendet.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(a).5",
    bsig_ref: "§ 30 Abs. 2 Nr. 1 BSIG",
    parent_ref: "Art. 21(2)(a)",
    category: "Risikoanalyse & Sicherheitsrichtlinien",
    title: "Risikoregister gefuehrt",
    description: "Risiken sind erfasst, bewertet, einem Verantwortlichen zugeordnet und mit einer Behandlungsentscheidung versehen.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(a).6",
    bsig_ref: "§ 30 Abs. 2 Nr. 1 BSIG",
    parent_ref: "Art. 21(2)(a)",
    category: "Risikoanalyse & Sicherheitsrichtlinien",
    title: "Regelmaessige und anlassbezogene Ueberpruefung",
    description: "Turnus festgelegt (mindestens jaehrlich) und zusaetzlich bei wesentlichen Aenderungen — neue Anwendung, Dienstleisterwechsel, Vorfall, Umstrukturierung.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(a).7",
    bsig_ref: "§ 30 Abs. 2 Nr. 1 BSIG",
    parent_ref: "Art. 21(2)(a)",
    category: "Risikoanalyse & Sicherheitsrichtlinien",
    title: "Bedrohungslage wird verfolgt und bewertet",
    description: "Quellen sind benannt, ein Turnus ist festgelegt, Meldungen werden bewertet und einschlaegige Meldungen muenden in Risiken oder Aufgaben. Das Modul Bedrohungslage fuehrt diesen Nachweis.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(b).1",
    bsig_ref: "§ 30 Abs. 2 Nr. 2 BSIG",
    parent_ref: "Art. 21(2)(b)",
    category: "Vorfallbewältigung",
    title: "Sicherheitsvorfall definiert und abgegrenzt",
    description: "Was ein Sicherheitsvorfall ist und wie er sich von einer Betriebsstoerung unterscheidet, ist festgelegt. Ohne diese Abgrenzung entscheidet im Ernstfall jeder fuer sich, ob gemeldet wird.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(b).2",
    bsig_ref: "§ 30 Abs. 2 Nr. 2 BSIG",
    parent_ref: "Art. 21(2)(b)",
    category: "Vorfallbewältigung",
    title: "Rollen, Erreichbarkeiten und Eskalationsstufen",
    description: "Wer reagiert, wer entscheidet, wer eskaliert — mit Erreichbarkeit auch ausserhalb der Geschaeftszeiten.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(b).3",
    bsig_ref: "§ 30 Abs. 2 Nr. 2 BSIG",
    parent_ref: "Art. 21(2)(b)",
    category: "Vorfallbewältigung",
    title: "Erkennung und Protokollierung",
    description: "Sicherheitsrelevante Ereignisse werden zentral protokolliert, die Protokolle werden ausgewertet, und die Aufbewahrungsfrist ist festgelegt.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(b).4",
    bsig_ref: "§ 30 Abs. 2 Nr. 2 BSIG",
    parent_ref: "Art. 21(2)(b)",
    category: "Vorfallbewältigung",
    title: "Triage und Priorisierung",
    description: "Schweregrade und Reaktionszeiten sind definiert und an die Eskalation gekoppelt.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(b).5",
    bsig_ref: "§ 30 Abs. 2 Nr. 2 BSIG",
    parent_ref: "Art. 21(2)(b)",
    category: "Vorfallbewältigung",
    title: "Eindaemmung, Beseitigung und Wiederherstellung",
    description: "Fuer die wichtigsten Szenarien liegen Handlungsanweisungen vor, einschliesslich Beweissicherung vor dem Aufraeumen.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(b).6",
    bsig_ref: "§ 30 Abs. 2 Nr. 2 BSIG",
    parent_ref: "Art. 21(2)(b)",
    category: "Vorfallbewältigung",
    title: "Nachbereitung und Lessons Learned",
    description: "Jeder erhebliche Vorfall wird nachbereitet, Ursachen werden festgehalten und Massnahmen abgeleitet und nachverfolgt.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(b).7",
    bsig_ref: "§ 30 Abs. 2 Nr. 2 BSIG",
    parent_ref: "Art. 21(2)(b)",
    category: "Vorfallbewältigung",
    title: "Vorgehen geuebt",
    description: "Mindestens jaehrlich eine Uebung, mit Protokoll. Ein ungeuebter Plan ist eine Annahme, kein Verfahren.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(c).1",
    bsig_ref: "§ 30 Abs. 2 Nr. 3 BSIG",
    parent_ref: "Art. 21(2)(c)",
    category: "Business Continuity",
    title: "Kritische Prozesse und Auswirkungsanalyse",
    description: "Die Prozesse, deren Ausfall weh tut, sind erhoben; je Prozess sind Wiederanlaufzeit und tolerierbarer Datenverlust festgelegt.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 21(2)(c).2",
    bsig_ref: "§ 30 Abs. 2 Nr. 3 BSIG",
    parent_ref: "Art. 21(2)(c)",
    category: "Business Continuity",
    title: "Backup-Konzept",
    description: "Frequenz, Umfang, Aufbewahrungsdauer und getrennte beziehungsweise offline gehaltene Kopien sind schriftlich geregelt.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 21(2)(c).3",
    bsig_ref: "§ 30 Abs. 2 Nr. 3 BSIG",
    parent_ref: "Art. 21(2)(c)",
    category: "Business Continuity",
    title: "Wiederherstellung getestet",
    description: "Rueckspieltests mit Datum, Umfang und Ergebnis. Ein Backup zaehlt erst, wenn eine Wiederherstellung nachweislich funktioniert hat.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 21(2)(c).4",
    bsig_ref: "§ 30 Abs. 2 Nr. 3 BSIG",
    parent_ref: "Art. 21(2)(c)",
    category: "Business Continuity",
    title: "Notfall- und Wiederanlaufplaene",
    description: "Fuer die kritischen Systeme liegen Plaene vor, die auch dann benutzbar sind, wenn die eigene IT nicht zur Verfuegung steht.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 21(2)(c).5",
    bsig_ref: "§ 30 Abs. 2 Nr. 3 BSIG",
    parent_ref: "Art. 21(2)(c)",
    category: "Business Continuity",
    title: "Krisenmanagement und Krisenkommunikation",
    description: "Krisenstab benannt, Entscheidungswege und Erreichbarkeiten festgehalten, Kommunikationsvorlagen vorbereitet.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 21(2)(c).6",
    bsig_ref: "§ 30 Abs. 2 Nr. 3 BSIG",
    parent_ref: "Art. 21(2)(c)",
    category: "Business Continuity",
    title: "Redundanzen und Ausweichkapazitaeten",
    description: "Fuer die Prozesse mit der kuerzesten Wiederanlaufzeit ist geklaert, worauf ausgewichen wird und wie lange das traegt.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 21(2)(d).1",
    bsig_ref: "§ 30 Abs. 2 Nr. 4 BSIG",
    parent_ref: "Art. 21(2)(d)",
    category: "Lieferkettensicherheit",
    title: "Dienstleisterverzeichnis mit Kritikalitaet",
    description: "Alle Anbieter mit Zugriff auf Systeme oder Daten sind erfasst und nach ihrer Bedeutung fuer den Betrieb eingestuft.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(d).2",
    bsig_ref: "§ 30 Abs. 2 Nr. 4 BSIG",
    parent_ref: "Art. 21(2)(d)",
    category: "Lieferkettensicherheit",
    title: "Sicherheitsanforderungen vertraglich vereinbart",
    description: "Standardklauseln zu Meldepflicht bei Vorfaellen, Auskunfts- und Auditrechten, Subunternehmern sowie Rueckgabe und Loeschung von Daten.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(d).3",
    bsig_ref: "§ 30 Abs. 2 Nr. 4 BSIG",
    parent_ref: "Art. 21(2)(d)",
    category: "Lieferkettensicherheit",
    title: "Sicherheitsbewertung vor Beauftragung",
    description: "Vor der Vergabe wird geprueft und dokumentiert, welches Risiko der Anbieter mitbringt.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(d).4",
    bsig_ref: "§ 30 Abs. 2 Nr. 4 BSIG",
    parent_ref: "Art. 21(2)(d)",
    category: "Lieferkettensicherheit",
    title: "Laufende Ueberwachung und Nachweise",
    description: "Je nach Kritikalitaet Zertifikate, Pruefberichte oder eigene Audits — mit Eingang, Gueltigkeit und Bewertung.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(d).5",
    bsig_ref: "§ 30 Abs. 2 Nr. 4 BSIG",
    parent_ref: "Art. 21(2)(d)",
    category: "Lieferkettensicherheit",
    title: "Ausstiegs- und Wechselstrategie",
    description: "Fuer kritische Anbieter ist geklaert, wie ein Wechsel oder Ausfall aufgefangen wird, inklusive Datenrueckgabe.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(e).1",
    bsig_ref: "§ 30 Abs. 2 Nr. 5 BSIG",
    parent_ref: "Art. 21(2)(e)",
    category: "Sicherheit im Erwerb",
    title: "Sicherheitsanforderungen in der Beschaffung",
    description: "Eine verbindliche Checkliste fuer IT-Beschaffungen: Standardpasswoerter, Update-Faehigkeit, Supportzeitraum, Schnittstellen, Protokollierung.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(e).2",
    bsig_ref: "§ 30 Abs. 2 Nr. 5 BSIG",
    parent_ref: "Art. 21(2)(e)",
    category: "Sicherheit im Erwerb",
    title: "Sichere Entwicklung",
    description: "Wo selbst entwickelt wird: getrennte Umgebungen, Codepruefung, Umgang mit Abhaengigkeiten und Geheimnissen, schriftlich festgehalten.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(e).3",
    bsig_ref: "§ 30 Abs. 2 Nr. 5 BSIG",
    parent_ref: "Art. 21(2)(e)",
    category: "Sicherheit im Erwerb",
    title: "Aenderungsmanagement",
    description: "Aenderungen an produktiven Systemen werden beantragt, bewertet, freigegeben und dokumentiert — mit Rueckfallweg.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(e).4",
    bsig_ref: "§ 30 Abs. 2 Nr. 5 BSIG",
    parent_ref: "Art. 21(2)(e)",
    category: "Sicherheit im Erwerb",
    title: "Schwachstellenmanagement",
    description: "Quellen, Bewertung, Zustaendigkeiten und Fristen je Schweregrad sind festgelegt; der Abgleich gegen das eigene Inventar laeuft.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(e).5",
    bsig_ref: "§ 30 Abs. 2 Nr. 5 BSIG",
    parent_ref: "Art. 21(2)(e)",
    category: "Sicherheit im Erwerb",
    title: "Patchmanagement mit Fristen",
    description: "Fristen je Schweregrad, Eskalation bei Ueberschreitung, begruendete und befristete Ausnahmen.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(e).6",
    bsig_ref: "§ 30 Abs. 2 Nr. 5 BSIG",
    parent_ref: "Art. 21(2)(e)",
    category: "Sicherheit im Erwerb",
    title: "Umgang mit Supportende",
    description: "Systeme ohne Herstellerunterstuetzung sind bekannt, bewertet und mit einem Ablauf- oder Kompensationsplan versehen.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(e).7",
    bsig_ref: "§ 30 Abs. 2 Nr. 5 BSIG",
    parent_ref: "Art. 21(2)(e)",
    category: "Sicherheit im Erwerb",
    title: "Offenlegung von Schwachstellen",
    description: "Eine erreichbare Kontaktstelle fuer Hinweise von aussen und ein Verfahren, wie damit umgegangen wird.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(f).1",
    bsig_ref: "§ 30 Abs. 2 Nr. 6 BSIG",
    parent_ref: "Art. 21(2)(f)",
    category: "Wirksamkeit von Maßnahmen",
    title: "Kennzahlen definiert und ausgewertet",
    description: "Eine ueberschaubare Zahl aussagefaehiger Kennzahlen, regelmaessig erhoben und besprochen — Patchstand, offene kritische Risiken, Schulungsquote, Reaktionszeiten.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 21(2)(f).2",
    bsig_ref: "§ 30 Abs. 2 Nr. 6 BSIG",
    parent_ref: "Art. 21(2)(f)",
    category: "Wirksamkeit von Maßnahmen",
    title: "Internes Auditprogramm",
    description: "Ein Plan ueber das Jahr, wer was wann prueft, mit Ergebnissen und abgeleiteten Massnahmen.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 21(2)(f).3",
    bsig_ref: "§ 30 Abs. 2 Nr. 6 BSIG",
    parent_ref: "Art. 21(2)(f)",
    category: "Wirksamkeit von Maßnahmen",
    title: "Technische Pruefungen",
    description: "Schwachstellenscans und, fuer exponierte Systeme, Penetrationstests — mit Nachverfolgung der Feststellungen.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 21(2)(f).4",
    bsig_ref: "§ 30 Abs. 2 Nr. 6 BSIG",
    parent_ref: "Art. 21(2)(f)",
    category: "Wirksamkeit von Maßnahmen",
    title: "Managementbewertung",
    description: "Die Leitung bewertet die Wirksamkeit in festgelegtem Turnus und haelt Entscheidungen fest.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 21(2)(g).1",
    bsig_ref: "§ 30 Abs. 2 Nr. 7 BSIG",
    parent_ref: "Art. 21(2)(g)",
    category: "Cyberhygiene & Schulungen",
    title: "Schulungskonzept mit Zielgruppen und Turnus",
    description: "Wer wird wie oft womit geschult — unterschieden nach Beschaeftigten, Administratoren, Entwicklern und Leitung.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(g).2",
    bsig_ref: "§ 30 Abs. 2 Nr. 7 BSIG",
    parent_ref: "Art. 21(2)(g)",
    category: "Cyberhygiene & Schulungen",
    title: "Grundschulung vor dem ersten Zugriff",
    description: "Neueintritte werden geschult, bevor sie Zugriff erhalten, nicht irgendwann danach.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(g).3",
    bsig_ref: "§ 30 Abs. 2 Nr. 7 BSIG",
    parent_ref: "Art. 21(2)(g)",
    category: "Cyberhygiene & Schulungen",
    title: "Wiederkehrende Sensibilisierung",
    description: "Laufende Massnahmen ueber das Jahr, nicht eine Pflichtveranstaltung im Dezember.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(g).4",
    bsig_ref: "§ 30 Abs. 2 Nr. 7 BSIG",
    parent_ref: "Art. 21(2)(g)",
    category: "Cyberhygiene & Schulungen",
    title: "Teilnahme nachgewiesen",
    description: "Teilnehmer, Inhalt, Datum und naechster Termin sind dokumentiert.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(g).5",
    bsig_ref: "§ 30 Abs. 2 Nr. 7 BSIG",
    parent_ref: "Art. 21(2)(g)",
    category: "Cyberhygiene & Schulungen",
    title: "IT-Nutzungsrichtlinie",
    description: "Kurz, lesbar, zentral verfuegbar, Kenntnisnahme erfasst.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(h).1",
    bsig_ref: "§ 30 Abs. 2 Nr. 8 BSIG",
    parent_ref: "Art. 21(2)(h)",
    category: "Kryptografie",
    title: "Kryptokonzept",
    description: "Welche Verfahren fuer welchen Schutzbedarf, mit Mindeststaerken und einem Plan fuer die Abloesung veralteter Verfahren.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(h).2",
    bsig_ref: "§ 30 Abs. 2 Nr. 8 BSIG",
    parent_ref: "Art. 21(2)(h)",
    category: "Kryptografie",
    title: "Verschluesselung bei der Uebertragung",
    description: "Transportverschluesselung fuer interne wie externe Verbindungen, mit definierten Mindestanforderungen.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(h).3",
    bsig_ref: "§ 30 Abs. 2 Nr. 8 BSIG",
    parent_ref: "Art. 21(2)(h)",
    category: "Kryptografie",
    title: "Verschluesselung bei der Speicherung",
    description: "Datentraeger, Backups und mobile Geraete, gekoppelt an die Klassifizierung der Daten.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(h).4",
    bsig_ref: "§ 30 Abs. 2 Nr. 8 BSIG",
    parent_ref: "Art. 21(2)(h)",
    category: "Kryptografie",
    title: "Schluesselverwaltung",
    description: "Erzeugung, Verteilung, Wechsel, Widerruf und Hinterlegung sind geregelt und einem Verantwortlichen zugeordnet. Der Widerruf fehlt am haeufigsten und kostet im Ernstfall am meisten.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(i).1",
    bsig_ref: "§ 30 Abs. 2 Nr. 9 BSIG",
    parent_ref: "Art. 21(2)(i)",
    category: "Personalsicherheit & Zugangssteuerung",
    title: "Asset-Inventar vollstaendig",
    description: "Hardware, Software, Cloud-Dienste und mobile Geraete, je Eintrag ein Verantwortlicher. Schatten-IT muss aktiv erfragt werden.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(i).2",
    bsig_ref: "§ 30 Abs. 2 Nr. 9 BSIG",
    parent_ref: "Art. 21(2)(i)",
    category: "Personalsicherheit & Zugangssteuerung",
    title: "Klassifizierung der Informationen",
    description: "Schutzklassen definiert, zugeordnet und mit Handhabungsregeln hinterlegt.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(i).3",
    bsig_ref: "§ 30 Abs. 2 Nr. 9 BSIG",
    parent_ref: "Art. 21(2)(i)",
    category: "Personalsicherheit & Zugangssteuerung",
    title: "Rollen- und Rechtekonzept",
    description: "Berechtigungen folgen Rollen, nicht Personen, und dem Prinzip der minimalen Rechte.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(i).4",
    bsig_ref: "§ 30 Abs. 2 Nr. 9 BSIG",
    parent_ref: "Art. 21(2)(i)",
    category: "Personalsicherheit & Zugangssteuerung",
    title: "Prozess fuer Eintritt, Wechsel und Austritt",
    description: "Besonders der Entzug beim Austritt und beim internen Wechsel, mit Frist und Nachweis.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(i).5",
    bsig_ref: "§ 30 Abs. 2 Nr. 9 BSIG",
    parent_ref: "Art. 21(2)(i)",
    category: "Personalsicherheit & Zugangssteuerung",
    title: "Rezertifizierung der Berechtigungen",
    description: "In festgelegtem Turnus bestaetigen die Verantwortlichen, wer welchen Zugriff behalten soll.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(i).6",
    bsig_ref: "§ 30 Abs. 2 Nr. 9 BSIG",
    parent_ref: "Art. 21(2)(i)",
    category: "Personalsicherheit & Zugangssteuerung",
    title: "Privilegierte Zugaenge gesondert geregelt",
    description: "Administrative Konten getrennt von persoenlichen, Verwendung protokolliert, Zugriff beschraenkt.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(i).7",
    bsig_ref: "§ 30 Abs. 2 Nr. 9 BSIG",
    parent_ref: "Art. 21(2)(i)",
    category: "Personalsicherheit & Zugangssteuerung",
    title: "Personelle Sicherheitsmassnahmen",
    description: "Verpflichtung auf Vertraulichkeit, Regelungen fuer sicherheitsrelevante Positionen, Rueckgabe von Geraeten und Ausweisen.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(i).8",
    bsig_ref: "§ 30 Abs. 2 Nr. 9 BSIG",
    parent_ref: "Art. 21(2)(i)",
    category: "Personalsicherheit & Zugangssteuerung",
    title: "Wechseldatentraeger und mobile Geraete",
    description: "Regeln zur Nutzung, technisch flankiert — Sperrung, Verschluesselungszwang oder Einzelfreigabe.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(j).1",
    bsig_ref: "§ 30 Abs. 2 Nr. 10 BSIG",
    parent_ref: "Art. 21(2)(j)",
    category: "Multi-Faktor-Authentifizierung",
    title: "Mehrfaktor fuer privilegierte Zugaenge",
    description: "Administrative Konten sind ohne zweiten Faktor nicht nutzbar.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(j).2",
    bsig_ref: "§ 30 Abs. 2 Nr. 10 BSIG",
    parent_ref: "Art. 21(2)(j)",
    category: "Multi-Faktor-Authentifizierung",
    title: "Mehrfaktor fuer Fernzugriff und Cloud",
    description: "Alles, was von aussen erreichbar ist, verlangt einen zweiten Faktor.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(j).3",
    bsig_ref: "§ 30 Abs. 2 Nr. 10 BSIG",
    parent_ref: "Art. 21(2)(j)",
    category: "Multi-Faktor-Authentifizierung",
    title: "Gesicherte Sprach-, Video- und Textkommunikation",
    description: "Zulaessige Werkzeuge sind benannt, ihre Verschluesselung ist geprueft, die Nutzung geregelt.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(2)(j).4",
    bsig_ref: "§ 30 Abs. 2 Nr. 10 BSIG",
    parent_ref: "Art. 21(2)(j)",
    category: "Multi-Faktor-Authentifizierung",
    title: "Notfallkommunikation",
    description: "Ein Weg, der auch dann traegt, wenn die eigene Infrastruktur ausgefallen oder kompromittiert ist — unabhaengig vom Hauptsystem und vorher erprobt.",
    applicability: { essential: 'required', important: 'required', indirect: 'required' },
  },
  {
    article_ref: "Art. 21(3).1",
    parent_ref: "Art. 21(3)",
    category: "Lieferkettensicherheit",
    title: "Schwachstellen und Praxis je Anbieter bewertet",
    description: "Die Bewertung beruecksichtigt die spezifischen Schwachstellen des Anbieters, die Qualitaet seiner Produkte und seine Sicherheitspraxis.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 21(3).2",
    parent_ref: "Art. 21(3)",
    category: "Lieferkettensicherheit",
    title: "Ergebnisse koordinierter Risikobewertungen beruecksichtigt",
    description: "Soweit auf Unionsebene oder national Bewertungen kritischer Lieferketten vorliegen, fliessen sie in die eigene Bewertung ein.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 21(4).1",
    parent_ref: "Art. 21(4)",
    category: "Korrekturmassnahmen",
    title: "Feststellungen zentral gefuehrt",
    description: "Maengel aus Audits, Tests, Vorfaellen und Meldungen laufen an einer Stelle zusammen.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 21(4).2",
    parent_ref: "Art. 21(4)",
    category: "Korrekturmassnahmen",
    title: "Korrekturmassnahmen mit Verantwortlichen und Fristen",
    description: "Je Feststellung eine Massnahme, ein Verantwortlicher, eine Frist und ein Status.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 21(4).3",
    parent_ref: "Art. 21(4)",
    category: "Korrekturmassnahmen",
    title: "Wirksamkeit der Korrektur geprueft",
    description: "Der Abschluss wird geprueft, nicht nur gemeldet.",
    applicability: { essential: 'required', important: 'required', indirect: 'recommended' },
  },
  {
    article_ref: "Art. 23(1).1",
    parent_ref: "Art. 23(1)",
    category: "Meldepflichten",
    title: "Interner Meldeweg festgelegt",
    description: "Wer meldet, an wen, auf welchem Weg und in welcher Frist — schriftlich und bekannt gemacht.",
    applicability: { essential: 'required', important: 'required', indirect: 'not_applicable' },
  },
  {
    article_ref: "Art. 23(1).2",
    parent_ref: "Art. 23(1)",
    category: "Meldepflichten",
    title: "Zugang zum Meldeverfahren eingerichtet",
    description: "Die Einrichtung ist bei der zustaendigen Stelle registriert und die Zugangsdaten zum Meldeportal sind hinterlegt und erreichbar. Im Ernstfall ist keine Zeit, das erst einzurichten.",
    applicability: { essential: 'required', important: 'required', indirect: 'not_applicable' },
  },
  {
    article_ref: "Art. 23(1).3",
    parent_ref: "Art. 23(1)",
    category: "Meldepflichten",
    title: "Kriterien fuer einen erheblichen Vorfall",
    description: "Woran erkannt wird, dass die Meldeschwelle erreicht ist, ist festgelegt — sonst wird die 24-Stunden-Frist verpasst, waehrend diskutiert wird.",
    applicability: { essential: 'required', important: 'required', indirect: 'not_applicable' },
  },
  {
    article_ref: "Art. 23(2).1",
    parent_ref: "Art. 23(2)",
    category: "Meldepflichten",
    title: "Inhalte der 72-Stunden-Meldung vorbereitet",
    description: "Erste Bewertung, Schweregrad, Auswirkungen und gegebenenfalls Kompromittierungsindikatoren — als Vorlage vorbereitet.",
    applicability: { essential: 'required', important: 'required', indirect: 'not_applicable' },
  },
  {
    article_ref: "Art. 23(4).1",
    parent_ref: "Art. 23(4)",
    category: "Meldepflichten",
    title: "Abschlussbericht vorbereitet",
    description: "Beschreibung des Vorfalls, Ursache, ergriffene Massnahmen und grenzueberschreitende Auswirkungen — als Vorlage, nicht erst im Ernstfall entworfen.",
    applicability: { essential: 'required', important: 'required', indirect: 'not_applicable' },
  },
];

module.exports = catalog;
